### ISSUE TITLE
Calls with cupy arrays is creating unwanted extra memories. 

### ISSUE THREAD

**Issue by chaithyagr** [mind-inria/mri-nufft#108]
Interface observed: `gpuNUFFT`, could potentially impact others also as it seems cupy issue

I recently saw nearly double to triple the usage of GPU memory than what was needed. On closely checking, I think the problem is when we try to convert a cupy array to `complex64`

https://github.com/mind-inria/mri-nufft/blob/8e15f052773295eee3224dd2455805d43ab11525/src/mrinufft/operators/interfaces/gpunufft.py#L311

This causes creation of new unwanted memory. We need a better converter, which should either delete the earlier memory or not even create one in the ideal scenario that we give the right datasizes. I feel we need a to complex64 as a specific separate utils function to handle this.

**Comment by paquiteau** [comment]
There might be more to it: Cupy does its own memory pooling, so the increasing might come from this (allocating new memory instead of reusing the one in the pool)[^1] 

However this remains a bug: `astype` as `copy=True` by default (arrgh) [^2], unlike in numpy.


[^1]: https://docs.cupy.dev/en/stable/user_guide/memory.html
[^2]: https://docs.cupy.dev/en/stable/reference/generated/cupy.ndarray.html#cupy.ndarray.astype
